<?php

return [
    [
        'id' => 'phase1-render-smoke',
        'path' => __DIR__ . '/integration/test_phase1.php',
        'label' => 'Phase 1 render smoke',
        'description' => 'Prueft klassische Preview-/Generator-Basics und Shared-CSS-Einbindung.',
        'suites' => ['smoke', 'render', 'classic', 'integration'],
    ],
    [
        'id' => 'phase2-wysiwyg-regression',
        'path' => __DIR__ . '/integration/test_phase2.php',
        'label' => 'Phase 2 WYSIWYG regression',
        'description' => 'Deckt Generator-, Tile-Meta- und fruehe WYSIWYG-/API-Regressionen ab.',
        'suites' => ['integration', 'render', 'api', 'editor', 'legacy-suite'],
    ],
    [
        'id' => 'phase3-editor-assets',
        'path' => __DIR__ . '/integration/test_phase3.php',
        'label' => 'Phase 3 editor assets',
        'description' => 'Prueft V2-Editor-Assets, Struktur und DnD-/Insert-Integration.',
        'suites' => ['integration', 'editor', 'frontend', 'assets'],
    ],
    [
        'id' => 'backup-service',
        'path' => __DIR__ . '/integration/test_backup_service.php',
        'label' => 'Backup service workflow',
        'description' => 'Snapshot-, Export-, Publish-, Quick-Restore- und Restore-Modi.',
        'suites' => ['integration', 'backup', 'service'],
    ],
    [
        'id' => 'narrow-layout',
        'path' => __DIR__ . '/integration/test_narrow.php',
        'label' => 'Narrow layout generation',
        'description' => 'Prueft Narrow-Layout-HTML/CSS-Generierung und Rueckbau der Settings.',
        'suites' => ['integration', 'render', 'layout', 'theme'],
    ],
    [
        'id' => 'v2-render-smoke',
        'path' => __DIR__ . '/integration/test_v2_render.php',
        'label' => 'V2 editor render smoke',
        'description' => 'PHP-Render-Smoke-Test fuer backend/v2/editor.php.',
        'suites' => ['smoke', 'editor', 'render', 'v2'],
    ],
    [
        'id' => 'v2-browser-boot-smoke',
        'path' => __DIR__ . '/integration/test_v2_browser_boot_smoke.php',
        'label' => 'V2 browser boot smoke',
        'description' => 'Startet einen lokalen PHP-Server und prueft den echten Modul-Bootpfad des V2-Editors in einem Headless-Browser.',
        'suites' => ['smoke', 'editor', 'frontend', 'browser', 'v2'],
    ],
    [
        'id' => 'section-render-contract',
        'path' => __DIR__ . '/integration/test_section_layout.php',
        'label' => 'Section render contract',
        'description' => 'Contract-Test fuer renderCanvasSections() und V2_CONFIG.renderedSections.',
        'suites' => ['contracts', 'render', 'editor', 'v2'],
    ],
    [
        'id' => 'render-canvas-layout-endpoint',
        'path' => __DIR__ . '/integration/test_render_canvas_layout_endpoint.php',
        'label' => 'render_canvas_layout endpoint contract',
        'description' => 'Vergleicht den API-Endpunkt render_canvas_layout mit GeneratorService::renderCanvasSections().',
        'suites' => ['contracts', 'api', 'render', 'v2'],
    ],
    [
        'id' => 'render-all-tiles-endpoint',
        'path' => __DIR__ . '/integration/test_render_all_tiles_html_endpoint.php',
        'label' => 'render_all_tiles_html endpoint contract',
        'description' => 'Vergleicht den API-Endpunkt render_all_tiles_html mit GeneratorService::renderAllTilesHtml().',
        'suites' => ['contracts', 'api', 'render', 'v2'],
    ],
    [
        'id' => 'auth-service-contract',
        'path' => __DIR__ . '/integration/test_auth_service_contract.php',
        'label' => 'AuthService contract',
        'description' => 'Prueft generische Login-Antworten, Code-Validierung, Lockout und Session-Expiry von AuthService.',
        'suites' => ['contracts', 'auth', 'service', 'integration'],
    ],
    [
        'id' => 'upload-service-contract',
        'path' => __DIR__ . '/integration/test_upload_service_contract.php',
        'label' => 'UploadService contract',
        'description' => 'Prueft Upload-Validierung sowie List/Delete-Verhalten von UploadService.',
        'suites' => ['contracts', 'upload', 'service', 'integration'],
    ],
    [
        'id' => 'settings-endpoints',
        'path' => __DIR__ . '/integration/test_settings_endpoints.php',
        'label' => 'Settings endpoints contract',
        'description' => 'Vergleicht get_settings/save_settings mit SettingsService und prueft normalisierte Settings-Antworten.',
        'suites' => ['contracts', 'api', 'settings', 'integration'],
    ],
    [
        'id' => 'admin-endpoints',
        'path' => __DIR__ . '/integration/test_admin_endpoints.php',
        'label' => 'Admin endpoints contract',
        'description' => 'Prueft get_admins, invite_admin und die Remove-Actions gegen AuthService und Session-Sonderfaelle.',
        'suites' => ['contracts', 'api', 'auth', 'admin', 'integration'],
    ],
    [
        'id' => 'system-endpoints',
        'path' => __DIR__ . '/integration/test_system_endpoints.php',
        'label' => 'System endpoints contract',
        'description' => 'Prueft extend_session und check_permissions gegen Session- und SecurityHelper-Verhalten.',
        'suites' => ['contracts', 'api', 'system', 'integration'],
    ],
    [
        'id' => 'tile-crud-endpoints',
        'path' => __DIR__ . '/integration/test_tile_crud_endpoints.php',
        'label' => 'Tile CRUD endpoints contract',
        'description' => 'Prueft get_tiles/get_tile/save_tile/update_positions/delete_tile gegen TileService.',
        'suites' => ['contracts', 'api', 'crud', 'integration', 'editor'],
    ],
    [
        'id' => 'legal-footer-render',
        'path' => __DIR__ . '/integration/test_legal_footer.php',
        'label' => 'Legal footer render contract',
        'description' => 'Prueft Footer- und Modal-Rendering fuer Impressum/Datenschutz inklusive Sanitizing und Route-Hooks.',
        'suites' => ['contracts', 'render', 'integration'],
    ],
    [
        'id' => 'iframe-modal-config',
        'path' => __DIR__ . '/integration/test_iframe_modal_config.php',
        'label' => 'Iframe modal config contract',
        'description' => 'Prueft Iframe-Modal-Datenattribute sowie CSS/JS-Prioritaets-Hooks fuer Background und Header.',
        'suites' => ['contracts', 'render', 'integration', 'iframe'],
    ],
    [
        'id' => 'unit-media-path-helper',
        'path' => __DIR__ . '/unit/test_media_path_helper.php',
        'label' => 'MediaPathHelper unit',
        'description' => 'Prueft reine Pfad-Normalisierung fuer Backend-Medienpfade ohne I/O-Kontext.',
        'suites' => ['unit', 'service', 'media'],
    ],
    [
        'id' => 'unit-render-contract',
        'path' => __DIR__ . '/unit/test_render_contract.php',
        'label' => 'RenderContract unit',
        'description' => 'Prueft die kanonische Key-Normalisierung und Fehlerfaelle von RenderContract.',
        'suites' => ['unit', 'contracts', 'render'],
    ],
    [
        'id' => 'e2e-login-v2-flow',
        'type' => 'manual',
        'path' => __DIR__ . '/e2e/login-v2-flow.md',
        'label' => 'Manual login to V2 flow',
        'description' => 'Manueller Browser-Flow fuer Login, Code-Verifikation und Redirect zum kanonischen V2-Editor.',
        'suites' => ['e2e', 'manual', 'auth', 'editor'],
    ],
    [
        'id' => 'e2e-legacy-editor-redirect',
        'type' => 'manual',
        'path' => __DIR__ . '/e2e/legacy-editor-redirect.md',
        'label' => 'Manual legacy editor redirect',
        'description' => 'Manueller Browser-Flow fuer Alt-URL /backend/editor.php und Redirect zum kanonischen V2-Editor.',
        'suites' => ['e2e', 'manual', 'legacy', 'editor'],
    ],
    [
        'id' => 'e2e-preview-publish-restore',
        'type' => 'manual',
        'path' => __DIR__ . '/e2e/preview-publish-restore.md',
        'label' => 'Manual preview publish restore flow',
        'description' => 'Manueller Browser-Flow fuer Vorschau, Veroeffentlichung und Quick-Restore.',
        'suites' => ['e2e', 'manual', 'render', 'backup', 'editor'],
    ],
];